pipeline {
    agent any
    parameters {
        choice(name: 'ENVIRONMENT', description: 'Select the Environemnt from the Dropdown List', choices: ['dev', 'pre', 'pro'])
        string(name: 'PLAYBOOK', description: 'Write the playbook file name without extension', defaultValue: 'my-example-playbook', trim: true)
        string(name: 'BRANCH_NAME', description: 'Write the branch name to deploy', defaultValue: 'master', trim: true)
    } //params
    stages {
        stage('Config') {
            steps {
                script {
                    step1(getRole("${ENVIRONMENT}"), 'jquintero-${ENVIRONMENT}-devops')
                    step2("${ENVIRONMENT}")
                    echo "BRANCH_NAME = ${BRANCH_NAME}"
                } //script
            } //steps
         } //stage
        stage('Apply') {
            steps {
                script {
                    applyExample("${ENVIRONMENT}", "${PLAYBOOK}")
                } //script
            } //steps
        } //stage
    }//stages
}//pipeline

//functions
def step1(String ROLE, String SESSION) {
    echo 'step1'
}

def step2(String ENVIRONMENT) {
    echo 'step2'
    echo "${ENVIRONMENT}-jquintero-pem"
    echo "${ENVIRONMENT}-jquintero-vault"
}

def getRole(String ENVIRONMENT) {
    String jquinteroRole = null
    switch (ENVIRONMENT) {
        case 'dev':
            jquinteroRole = 'arn:aws:iam::12345678910:role/dev-jquintero-devops'
            break
        case 'pre':
            jquinteroRole = 'arn:aws:iam::12345678910:role/dev-jquintero-devops'
            break
        case 'pro':
            jquinteroRole = 'arn:aws:iam::12345678910:role/pro-jquintero-devops'
            break
    } //case
    return jquinteroRole
}


def applyExample(String ENVIRONMENT, String PLAYBOOK) {
    echo "${ENVIRONMENT}"
    echo "${PLAYBOOK}"
    playbookFile = "${PLAYBOOK}.yml"
    echo "${playbookFile}"
}